name: cheftrack_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & HTTP (updated versions)
  http: ^1.1.0
  
  # UI
  cupertino_icons: ^1.0.6

  # Storage
  shared_preferences: ^2.2.2

  # Permissions & camera scanning (updated versions)
  permission_handler: ^11.0.1
  mobile_scanner: ^3.5.6

  # Image & text (updated versions)
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  
  # ML Kit with compatible namespace versions
  google_mlkit_text_recognition: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

# Force compatible ML Kit versions to avoid namespace issues
dependency_overrides:
  google_mlkit_commons: ^0.7.1
  google_mlkit_text_recognition: ^0.13.0

# Optional: Add assets if you have any in the future
# flutter:
#   assets:
#     - images/
#     - icons/